### ISSUE TITLE
Incorrect Reference

### ISSUE THREAD

**Issue by jeanpaulrobineau** [mollie/mollie-odoo#1]
Hello,

There is an incorrect reference in the file /views/mollie.xml to /payment_mollie_beopen
at line  25
<img t-if="not submit_txt" src="/payment_mollie_beopen/static/src/img/mollie_icon.png"/>

kind regards

**Comment by willemstuursma** [comment]
Thanks @jeanpaulrobineau. Could you create a pull request, or help us make the right change?

**Comment by jeanpaulrobineau** [comment]
I have found even other wrong references so i have created 2 pull requests

**Comment by Smitsel** [comment]
Thank you
