### ISSUE TITLE
[10.0] Mollie payment status not always fetched/updated

### ISSUE THREAD

**Issue by Yenthe666** [mollie/mollie-odoo#10]
Hi guys,

We've found a case in the mollie module in which the mollie payment is found and referenced but where the state of the mollie payment is not updated in Odoo.
The order correctly links to the payment method:
![image](https://user-images.githubusercontent.com/6352350/39111209-a599000c-46d4-11e8-94c3-43f67386f5ad.png)

The state of the payment order is in in concept:
![image](https://user-images.githubusercontent.com/6352350/39111270-d2b4b4aa-46d4-11e8-83e7-614b54af9b54.png)

When looking at the payment details on Mollie itself you can see that the payment is paid and everything is done:
![image](https://user-images.githubusercontent.com/6352350/39111362-20be5912-46d5-11e8-9bb7-37ac70201aa4.png)

Do you guys have any clue? Is there any reason why there is no scheduler that checks all payments once a day if they're in the state concept for example?

**Comment by Yenthe666** [comment]
@Smitsel could I ask you to have a look at this please? We can't find the core problem of this one.

**Comment by Smitsel** [comment]
I've checked the payment and see that the webhookUrl is missing from the payment.
This is the url we call upon completing payment and status changes.

Normally the return URL wouldve updated it, but in the case where after payment a customer does not return to the webpage but closes the browser, no payment status is updated in odoo.

@huysmki do you know why the following line has been commented out?
https://github.com/mollie/mollie-odoo/blob/d499c47866bb6e8f407927e2730b8bb5a1ff3993/payment_mollie_official/controllers/main.py#L68

**Comment by Smitsel** [comment]
I don't have a working odoo environment since this is being done by another party.
However, if you uncomment that line mentioned above @Yenthe666 it should work, can you confirm this?

**Comment by Yenthe666** [comment]
Hi @Smitsel,

I'm curious though. Why do 99%+ of the orders succeed and once in a blue moon one fails?
Could you explain me what exactly the `webhookUrl` does or why it is (was) used?
I don't really know the module in detail and haven't deployed it for our customer so I'd like to know a bit more.

**Comment by Smitsel** [comment]
The best explanation can be found here:
https://www.mollie.com/nl/docs/webhook

And to answer your question about the situational fails, this can happen when a customer pays the order and then closes their browser, and thus not visiting the return page which updates your status :)

**Comment by Yenthe666** [comment]
@Smitsel,

Thanks a lot for the feedback, that does make sense. Regarding the example at the bottom of https://www.mollie.com/nl/docs/webhook it contains `order_nr = payment['metadata']['order_nr']` but `order_nr` is no longer in the `metadata`, it has become `order_id`, so you might want to change the docs.

If I now add the `webhookUrl` again it will not update this record anymore since it is weeks old, no?

**Comment by Smitsel** [comment]
You could ask our Support department to trigger the webhook for that payment if you supply them with your transaction id.

**Comment by Smitsel** [comment]
Please let me know if this works for you so we can make the changes to the repository :)

**Comment by Yenthe666** [comment]
@Smitsel thanks for the feedback. I've uncommented the webhookURL and requested a retrigger of the webhook url from the Mollie support form.
Could you get this moving faster? Not sure what response times are.

I'll give you feedback when this is tested.

**Comment by Yenthe666** [comment]
@Smitsel sadly my ticket cannot be done by Mollie because they have no webhookurl at your end so they cannot retrigger.
I've changed the customer his module to include the webhookUrl and I'll keep an eye out to see if this resolves it.

**Comment by Smitsel** [comment]
Allright, keep us posted.
