### ISSUE TITLE
No way to add transaction fees

### ISSUE THREAD

**Issue by Yenthe666** [mollie/mollie-odoo#104]
Imagine that you enable the option "Mastercard" and you get a non-EU customer. 
In this case the cost from Mollie is `€ 0.25 + 2.8 %`.
This can be quite a huge amount of your profit if you run this in a sector with low profits.

It would be great that in Odoo you'd have the option to define additional payment fees (and per payment method). Just like the `PayPal` app in Odoo does:
![image](https://user-images.githubusercontent.com/6352350/113517617-57b91800-9581-11eb-868c-ac8761d28c28.png)

**Comment by odoo-mvds** [comment]
This has been released in the new release. (v12 & 13 coming later next week)

**Comment by Yenthe666** [comment]
Thanks a lot 👍

**Comment by touchfix** [comment]
Any idea how we can add these transaction fee's to the invoice? Now these fee's are charged, but they are not added to the invoice, so the final amount is incorrect.
