### ISSUE TITLE
[13.0] The model mollie.voucher.line has no _description

### ISSUE THREAD

**Issue by ploegvde** [mollie/mollie-odoo#108]
Warning when using the module on Odoo.sh

The model mollie.voucher.line has no _description

**Comment by AmandaMollie** [comment]
@odoo-mvds - can you take a look at this one?

**Comment by odoo-mvds** [comment]
Hello,

you can ignore the warning, it's not a real issue. It will be fixed in the new release to avoid spoofing the logs.

br,
