### ISSUE TITLE
Import Module fails

### ISSUE THREAD

**Issue by MHaendel** [mollie/mollie-odoo#11]
Hey,

I'm trying to import this module on a hosted instance via Odoo Studio.

Error while importing module 'payment_mollie_official'
Field mollie_api_key_test missing

**Comment by gclauwae** [comment]
Module is not tested via Odoo Studio.

**Comment by Yenthe666** [comment]
Hi @MHaendel,

I actually think you've misunderstood the functionality of this import function in Odoo. It is not built to import whole Odoo modules, it can only load XML/JS/CSS, not modules with Python code.
You can only use these kind of modules after adding them to the server and updating the modules list.

CC @martijnpolder  - this one can be closed.

Regards,
Yenthe
