### ISSUE TITLE
[12.0] "Pay & Confirm" button from offer does not work - part2

### ISSUE THREAD

**Issue by marcinkuk** [mollie/mollie-odoo#117]
Previous issue:
https://github.com/mollie/mollie-odoo/issues/109

Hi,

sorry for the delay.
We had to update odoo to the latest build and fix "https" issue.

The problem still exist.
Clicking "Pay and Confirm" button doesn't nothing.

Odoo 12.0-20210809
Mollie Payments 12.0.1.6
Metadata in html with https

Can you help me?

**Comment by odoo-mvds** [comment]
@marcinkuk hi, is this issue still present? If so we can fix a quick call to go through your issue? br

**Comment by marcinkuk** [comment]
> @marcinkuk hi, is this issue still present? If so we can fix a quick call to go through your issue? br

Hi, we resolved the issue .
The problem was we didn't choose journal registy in mollie settings. There is no information about in manual.

**Comment by odoo-mvds** [comment]
hi, ok good to hear it's solved. Actually this filed is mandatory for every payment acquirer in odoo. But it's good to mention this in the manual as well. We'll take it into account.

Have a nice day!
