### ISSUE TITLE
Request : migration to V15

### ISSUE THREAD

**Issue by Xynklon** [mollie/mollie-odoo#118]
Would be great to have a version 15 one. :)

Thank you !

**Comment by gclauwae** [comment]
Now standard app in Odoo v15 😉👍

Op vr 22 okt. 2021 23:46 schreef Xynklon ***@***.***>:

**Comment by Xynklon** [comment]
The standard Mollie in odoo 15 goes to a Page not Found ( both live and test api) you only need to give api key .

**Comment by Yenthe666** [comment]
Plus v15 in Odoo is cripled against this app it's features :)

**Comment by odoo-mvds** [comment]
Hello. The extended version will be released Q1 22. Keep an eye on the app store for the release!

**Comment by odoo-mvds** [comment]
hi, the new module has been released. It's a add-on that adds the features from the full module on top of the native module.
