### ISSUE TITLE
QR code payments

### ISSUE THREAD

**Issue by delphinedevroe** [mollie/mollie-odoo#119]
Hello,
Odoo v15 offers the use of QR code payments on sales invoices.
Would it be possible to integrate Mollie QR code payments or payment links in the next version? 
Thanks!

**Comment by odoo-mvds** [comment]
Hello,

This function was released in the extended app this week for bancontact.

br,

**Comment by idealisconsultingbe** [comment]
![mollie](https://user-images.githubusercontent.com/2088903/156997583-ada1bdb9-614a-4b44-a0c6-31110ac1b0ce.png)
Hello, I have this error since the last commit. Did you made change in the mollie.js file?

**Comment by odoo-mvds** [comment]
Hello,

Could you try disabling mollie components? And let us know what happens?

Thanks,
Michael

**Comment by idealisconsultingbe** [comment]
It's working when I disabled the Mollie components.
What does it change to activate/deactivate the Mollie Components?

Kind Regards

**Comment by odoo-mvds** [comment]
Hello,

We need to analyse it further from our side.
What version are you using?

Thanks,

**Comment by idealisconsultingbe** [comment]
Odoo 14.0

In fact, when disabling/enabling again the Mollie components, I see a new field Mollie Profile ID, when I add my ID inside this field, it's working again.
