### ISSUE TITLE
[Question] Subscription support

### ISSUE THREAD

**Issue by KDederichs** [mollie/mollie-odoo#12]
Quick question, does this addon support the Odoo Enterprise Subscription Module?
The Module has an option to automatically collect the owed amount and I know Mollie also has support for recurring payments so I was wondering if the Addon supports this (since it's not stated anywhere if it does or not)

**Comment by Yenthe666** [comment]
Hi @KDederichs,

Sorry that nobody answered you earlier.
No, right now it does not support payments with subscriptions. It might be added in upcoming versions but won't be added before V13 for sure.
CC @martijnpolder  (can you close this one please?)

Regards,
Yenthe
