### ISSUE TITLE
can't reconcile mollie settlements and mollie deposits in my bank account

### ISSUE THREAD

**Issue by BramKuipers** [mollie/mollie-odoo#122]
Hi All,

I deployed the mollie settlements v14 on my odoo sh database bramkuipers-e-comkuipers1. However when I tried to contact the support of the integration the system said I did not download the third party app, which is strange because I did.

Anyhow, I would like to reconcile mollie deposits in my bank account with the mollie settlements integration but I do not understand how to reconcile them, see an example attached. Would be great if someone can help me with this issue.

If communication by e-mail or phone is easier, my e-mail address is Bram@bankhoezenspecialist.nl and my phone number is +31 6 48 89 91 95

Looking forward to any reply.

Kind regards,

Bram Kuipers

![Schermafbeelding 2022-02-18 om 12 41 17](https://user-images.githubusercontent.com/91030057/154676814-8494e07c-0b81-44b3-a95e-51bc9e60990f.png)

**Comment by odoo-mvds** [comment]
Hello Bram,

Did you follow the manual on how to configure the settlement module?
https://github.com/mollie/mollie-odoo/wiki/Mollie-Settlements-module

Because it seems you didn't do that part of the configuration yet?

Please follow all steps and let us know if something is not going as it should.

br,

**Comment by BramKuipers** [comment]
Hi Br,

Thanks for your response. I did actually follow the steps but I think I do nut fully understand how to reconcile mollie statements. See the pictures attached. I have multiple deposits from mollie into my bankaccount and I need to reconcile them somehow, unfortunately I do not know how I can do this. 

I encircled multiple deposits from mollie in my bank account, how can I reconcile them?

Looking forward to your reply.

Met vriendelijke groet,

Bram Kuipers 

www.bankhoezenspecialist.nl | ***@***.*** | +31 (0)85 060 54 03

**Comment by odoo-mvds** [comment]
Hello Bram,

If you have the Mollie Journal active. The you need to reconcile the payout from the Mollie Journal with the Payout received on your Bank Journal.
See this little schema.
<img width="829" alt="image" src="https://user-images.githubusercontent.com/59664044/158588559-efbe56ba-4a00-4c0e-9351-25614cdef946.png">
Actually, once you have correctly setup the Mollie Journal, it's classic accounting that needs to be done. You just need to understand that Mollie is considered as a different Bank Account.

Hope this help you,

**Comment by BramKuipers** [comment]
Hi Sir,

Thanks for your quick response and the extensive explanation. I understand what you are trying to say, unfortunately the amount of the payout and the total amount of the incoming orders is not exactly the same because of the fee’s that mollie has, so I can’t directly reconcile them right? 

Do you have time to have a short meeting where I can solve the issue, that would really help me :)

Looking forward to your reply. 

Met vriendelijke groet,

Bram Kuipers 

www.bankhoezenspecialist.nl | ***@***.*** | +31 (0)85 060 54 03

**Comment by odoo-mvds** [comment]
Hello,

in our settlement the fee and orders are seperated, so you should be able to reconcily full payments with orders.
We could schedule a meeting please send an email to odoo at applix.be

br,
