### ISSUE TITLE
mollie and odoo12 - settlement sync issues

### ISSUE THREAD

**Issue by batman1410** [mollie/mollie-odoo#123]
Hi...

we are currently using odoo v12. 

We installed the modules "mollie for odoo" and tried to sync the settlements after some configuration with the credentials.
According to the wiki here: "https://github.com/mollie/mollie-odoo/wiki/Mollie-Settlements-module", we need to set the token which we need to create in mollie. So far so good, but in odoo v12 we do not see the possibility to enter the token. The wiki-screenshot with the configuration form is slightly different in v12. What can we do?

**Comment by odoo-mvds** [comment]
Hello,

You need to installed the module "Mollie settlements sync" :  https://apps.odoo.com/apps/modules/12.0/mollie_account_sync/

br,
