### ISSUE TITLE
Importing unreferenced class

### ISSUE THREAD

**Issue by jwaes** [mollie/mollie-odoo#124]
https://github.com/mollie/mollie-odoo/blob/359ee5bfaad6a9a67ef5727fde6b8afc71fc570d/mollie_shipment_sync/models/payment_acquirer.py#L4

**Comment by jwaes** [comment]
https://github.com/mollie/mollie-odoo/pull/127

**Comment by odoo-mvds** [comment]
It is merged. Thank you for the PR
