### ISSUE TITLE
Support for SEPA

### ISSUE THREAD

**Issue by Yenthe666** [mollie/mollie-odoo#126]
Hi there,

If I'm not mistaking the Mollie app is not supporting SEPA payments in Odoo 14?
Is there any plan/roadmap for this or am I missing something?

**Comment by Yenthe666** [comment]
@odoo-mvds could I ask you for feedback about this one?

**Comment by Yenthe666** [comment]
@odoo-mvds this is kind of halting a project of us. Any chance you could give a quick feedback?

**Comment by odoo-mvds** [comment]
Hello,

For the moment this isn't on the roadmap yet. So it will not be very soon yet.
I'll update you in this ticket as soon as it's planned.

br,

**Comment by odoo-mvds** [comment]
https://github.com/mollie/mollie-odoo/issues/45 duplicate

**Comment by Koene5000100** [comment]
> Hello,
> 
> For the moment this isn't on the roadmap yet. So it will not be very soon yet. I'll update you in this ticket as soon as it's planned.
> 
> br,

Could i get informed aswel?
