### ISSUE TITLE
fees returns a dict when a float is required

### ISSUE THREAD

**Issue by baptisteghesquiere** [mollie/mollie-odoo#128]
The function mollie_compute_fees returns a dict when  if request and request.params.get('paymentmethod'): is false. ( line 52 in payment_acquirer.py )

Down the line odoo uses the return of this function to calculate and it expects a float.  When the dict is returned, the website breaks.

Please default to a float when the if statement fails.

**Comment by odoo-mvds** [comment]
Hello,

Can you provide the steps/video how this error is generated?
And is it for v14 version ?
