### ISSUE TITLE
Access rights in Accounting / Credit Notes

### ISSUE THREAD

**Issue by jwaes** [mollie/mollie-odoo#131]
After installing the Mollie app a button for initiating a refund is added to the Customer Credit Note form.
But this requires access to the `payment.acquirer` model. An access right that is not added to any Accounting group. This prevents Accounting users to access the credit note form.

As a quickfix i added the rights to Accounting group. But it would be nice if it was done during the installation of this module.

**Comment by odoo-mvds** [comment]
Thanks for reporting.

This issue is fixed in `v15.0.0.4`
It is also available on app store.
