### ISSUE TITLE
Mollie V15 Issue

### ISSUE THREAD

**Issue by cbatec** [mollie/mollie-odoo#132]
Hi I have installed Mollie in V15 and configured the API ...

When I try paying the fields under credit card cant be filled and I tried clicking on pay button anyway and i hangs for hours there loading.

**Comment by odoo-mvds** [comment]
Hello,

We would need more info.
Do you use the extended module?
Self hosted or odoo.sh?
Have you followed all steps in our wiki page?

thanks!

**Comment by odoo-mvds** [comment]
Hello, any update on this?

**Comment by cbatec** [comment]
It’s not working I can fillip the form with credit card details and name it is not giving the option to add the name when clicked on

Daly Babay
CBAtec 
USA: +16502167232
France: +33184808645

**Comment by odoo-mvds** [comment]
Hello,

ok can you give us more info about your installation?
Do you use the native app or the extended app? 
Self hosted or odoo online?

Thanks

**Comment by odoo-mvds** [comment]
Hi, 

If further assistance is needed. Please reply so we can try to reproduce the issue or look at your config.
Closing it for now.

br,
