### ISSUE TITLE
Mollie V14  invalid Mollie profile ID

### ISSUE THREAD

**Issue by eguane** [mollie/mollie-odoo#133]
Hi with the last version off mollie 14.0.0.10
when I try to edit or change any other payment acquirer, I can't save the change.
Invalid field mollie profile id.
![image](https://user-images.githubusercontent.com/35990301/192720729-b7dd17a9-42f7-4f89-9f6e-b33cd5c84edc.png)

Workarround, Desintalling the module mollie v14, change the payment acquirer, reinstall the module fix the issue !

**Comment by odoo-mvds** [comment]
Hello,

The profile ID is user when u want the credit card input during checkout of Odoo.
You should disable that option.

Do you have that enabled?

**Comment by eguane** [comment]
Hello thanks for you response.
As I can see mollie companents was checked wiht input the field profile id.
I have unchecked components but the problem is still present. 
![image](https://user-images.githubusercontent.com/35990301/193012833-71326997-ae7f-4042-ba85-ad607550985b.png)

**Comment by odoo-mvds** [comment]
ok, the UI has a little bug here. However, you can just put the profile ID, which is much quicker than your workaround.
We will update the UI in the next release.

br,

**Comment by eguane** [comment]
I put the correct profile ID and save it.
Issue always present when trying to edit any another payment acquirer.
Uninstall the module is the only good solution running for me.

**Comment by BartvandenHout** [comment]
change view: **acquirer_form_view_mollie**

                    <field name="mollie_profile_id" password="True" attrs="{'invisible': ['|', ('provider', '!=', 'mollie'), ('mollie_use_components', '=', False)], 'required':  ['&amp;', ('provider', '=', 'mollie'), ('mollie_use_components', '=', True)]}"/>
                    <label string=" " for="mollie_profile_id" attrs="{'invisible': ['|', ('provider', '!=', 'mollie'), ('mollie_use_components', '=', False)]}"> </label>

**Comment by odoo-mvds** [comment]
Hello,

Thanks for reporting this will be fixed in the new release.

br,

**Comment by odoo-mvds** [comment]
Hello,

The issue has been fixed in version `14.0.0.11` and update module available on app store.
Our team will forward port this for v15 too if necessary.  

Thanks for reporting.
