### ISSUE TITLE
plus that should not be in version 10.0

### ISSUE THREAD

**Issue by LucasCallista** [mollie/mollie-odoo#136]
We have an old client running on odoo 10 and this specific line crashes because there is a "+" charactar at the start splitting a dictionary ? This seems to be a typo:
https://github.com/mollie/mollie-odoo/blob/512b99d4c241100ea29ca3a7b37ea035ac612dab/payment_mollie_official/controllers/main.py#L68

**Comment by odoo-mvds** [comment]
Issue has been fix in latest update.
