### ISSUE TITLE
Issue on payment screen

### ISSUE THREAD

**Issue by bvanjeelharia** [mollie/mollie-odoo#142]
When incorrect details are entered on the payment screen for credit card , the page keeps on loading(UI gets blocked). Impacted Odoo versions: 15, 16

![Screenshot from 2023-10-04 16-59-28](https://github.com/mollie/mollie-odoo/assets/88703470/56841a21-34a5-4448-9fa0-ba0b264cba10)

**Comment by odoo-mvds** [comment]
The issue has been fixed in latest release, Thank you for reporting the issue.
