### ISSUE TITLE
order stuck in quotation status after payment

### ISSUE THREAD

**Issue by codeagencybe** [mollie/mollie-odoo#145]
Odoo version: 16.0

I notice when a payment is confirmed with Mollie via website checkout, the order status remains in "quotation" instead of "order". 
This means, every single web order has to be confirmed manually by an internal user. 

That doesn't seem to be normal behaviour? 
In the current use case, the client is using both manual quotations for B2B customers AND also online sales for B2C customers. 

Any plausible reason why the sale order gets stuck in quotation status while it's been paid succesfully online?

**Comment by odoo-mvds** [comment]
Hello,

This happens when you close the website page before redirecting back to Odoo.
However, Odoo will confirm the order afterwards using the cron:
<img width="914" alt="image" src="https://github.com/mollie/mollie-odoo/assets/59664044/650b92fe-4e0a-412c-929a-6b5e76967a6d">

This is not a bug, but standard Odoo behavior.

br,

**Comment by codeagencybe** [comment]
No that is the problem either. 
We already have this cronjob running every 10 minutes. 

But from what I found in the transaction details, it's a problem that only happens with Mollie. 

This is a more "extreme" example, but it shows you very good the problem. 

![image](https://github.com/mollie/mollie-odoo/assets/7568546/24711a00-6f57-4d2e-9e8e-6a705c832d34)

The initial payment attempt went wrong, for whatever reason. Sometimes it's a disruption at Mollie, sometimes it's because the customer has not enough money on the card (passing card limits for daily spending etc...) but in any case the payment fails. 
They redirect back eventually. 

And then comes the problem. Odoo creates sub-records as -1, -2, -3, ... which makes sense to me. 
But the problem is that we are seeing a big delay from Mollie coming back to confirm the final success payment. 
Sometimes it's even 12-14 hours later while if we check the Odoo account, the payment was already confirmed and captured 12+ hours earlier, except Odoo does not handle it's confirmation. 

So the merchant now has to manually check Mollie transaction lines one by one to find out which one have been paid but not registered yet in Odoo or go through the email confirmations they receive from Mollie. 
Because that is what we are experiencing. 
Mollie acknowledge successful payment, confirms by email but Odoo is not registering the payment and leaves the order in quotation. Even when the cronjob is running every 10 minutes. 


Do notice that the provider reference is also changing every payment.transaction record. I would expect this to remain the same? 

![image](https://github.com/mollie/mollie-odoo/assets/7568546/bb031a69-7b79-4a30-a622-789ce05322f5)


![image](https://github.com/mollie/mollie-odoo/assets/7568546/539f48aa-d223-45b4-b161-4664ada4cc59)


The chatter on the sale order is also full with these messages:

![image](https://github.com/mollie/mollie-odoo/assets/7568546/4af753a8-33ac-481a-8dcd-1c78f2692d43)


Here's another example:

The last confirmation message in the top shows up when Odoo received the final confirmation from Mollie and they are perfectly in sync. And this marks the website cart as "order" so it can be picked and shipped. 
The problem is that this final confirmation sometimes comes 14 hours or even 24 hours later. 
Not always but we can track this problem back when the original cart got breakdown into -1, -2, -3, ... 
For some reason, Odoo is causing a problem with Mollie on this specific behavior when the initial payment failed for whatever reason. 

We have also installed other payment gateways and simulated the same scenario, and it only happens for Mollie. 
We have also simulated the same scenario with WooCommerce and Magento with Mollie, and it only happens with Odoo. 

So I'm 300% confident and sure, this is a problem isolated to Odoo. 
At first we believed it only happened to big amounts as that is an easier trigger for a failed payment (card payment daily/weekly limit). So the customer has to abort payment and increase it's card spent limit first and then try pay for the cart again. 
But we were able to reproduce the same problem also for small amounts and again, only with combo Odoo + Mollie. 

![image](https://github.com/mollie/mollie-odoo/assets/7568546/4fde64f7-8a7d-4f94-aecc-28e578390f97)


For a small store, this might not be too much of a problem, but my client runs hundreds of orders per day. 
And if they don't get reliable payment confirmation, they are missing on shipping orders. Customers are calling them why their order didn't ship because they paid and got confirmation from Mollie, except Odoo wasn't able to process it. 
Then the abandoned cart email kicks of 4 hours later to that customer "they still have something in cart" while they already paid for that order making more chaos and confusion.

**Comment by odoo-mvds** [comment]
Hi,

the failed payment can be check on the backend of Mollie. That should give you an idea why you have up to 5 attempts before the validation of the payment.

In any case, when the payment is confirmed, and the flow of going back to the website is interrupted, it will break the creation of the invoice, and thus the confirmation of the SO.

The cron will only check orders that are in this state +12 hours (i'm not 100% sure, maybe it's even 24h) so even if you check every 10 minutes, it will ignore those fresh orders. 
This is the reason why it takes so long.

Again, this is default Odoo behavior with all payment providers.

br,

**Comment by codeagencybe** [comment]
> Hi,
> 
> the failed payment can be check on the backend of Mollie. That should give you an idea why you have up to 5 attempts before the validation of the payment.
> 

We already checked that. The reasons we see is due to card limit in 99,99% of the cases. 
But these customers do a new attempt after they raised the limit and at some point it works. 
The problem is after the successful payment, the confirmation from Mollie back to Odoo is delayed too much (12+ hours up to 24 hours). 
And it ONLY happens with Mollie. 
I don't believe this is a "default behavior" as other payment providers with Buckaroo and Stripe don't show this behavior at all. 

> In any case, when the payment is confirmed, and the flow of going back to the website is interrupted, it will break the creation of the invoice, and thus the confirmation of the SO.
> 

We don't have invoice creating enabled. Invoices are created after delivery manually. 
The problem is the order is already paid in Mollie systems, but comes delayed to Odoo in 12+ hours
which means, my customer their warehouse is late on shipping orders with minimum half a day. 


> The cron will only check orders that are in this state +12 hours (i'm not 100% sure, maybe it's even 24h) so even if you check every 10 minutes, it will ignore those fresh orders. This is the reason why it takes so long.
> 

Why would it ignore these fresh orders? That doesn't make any sense. 


> Again, this is default Odoo behavior with all payment providers.
> 

Clearly not, as Buckaroo and Stripe don't show these behavior. We have tested 5 different payment providers in Odoo under exactly same conditions. 
It only happens with Mollie. 

In the Mollie dashboard there is nothing wrong. 
We can see all the timestamps and the webhooks being fire off *immediately* with success. 
It's only Odoo that for some unknown reason is delaying the booking the of the payment that came back from Mollie to 12+ hours if some initial previous payment failed first. 


payment expired
this is the buyers intent mistake, they waited too long or they got some message in their bank app that payment could not work because of too high amount within their card spent limit. 

![image](https://github.com/mollie/mollie-odoo/assets/7568546/0e5fc01b-1a60-4c6b-a31f-7be8daaaebf1)


payment success:
here you can see the webhooks meta data on the bottom are updated with the new SO number. 
But in the right side history bar we see an email was sent immediately and the initial payment created but there is no webhook history that calls back. 
![image](https://github.com/mollie/mollie-odoo/assets/7568546/c8dade14-0ebc-4d97-9f91-cb2698df147a)


We are trying to understand where and how this difference comes from. 
None of the succesful paid orders show a webhook from Mollie to Odoo, only email notification. 
When the payment failed, it does do a callback for the failing
When the payment is success in 1 go, it's all good in Odoo
When the payment is repeat with sucess, it's a lost communication and no call back. 

According to Mollie support, they say the problem comes from Odoo as Odoo has to pass the callback request. 
If it doesn't, Mollie doesn't return a callback because Odoo didn't ask for it.

**Comment by odoo-mvds** [comment]
Hello,

If the webhook isn't called, the cron will confirm the SO as a fallback system, and if enabled (not in your case) generate the invoice.
The behavior i'm talking about ignoring the fresh orders can be found in the source code of Odoo. We also think this can be shorter, but it's not in the scope of Mollie, as it's default Odoo behavior. You can do this customisation easily by editing the behavior of that cron.

The main issue in your case, is that the customer, somehow, is not going back to the redirect URL after a succesfull payment. This can be due to the end user closing his window too soon, or if you have it in 100% of the cases, a misconfigured base URL.

If you have it only for a few cases, than most likely it's the user closing the payment screen too soon.

Your solution in that case, is to alter the default Odoo cron to check even the freshly created ordes, instead of ignoring them the first X hours. Then it will be confirmed after 10 minutes instead after 12h or more.

If you think this behavior is not ok, you should contact Odoo about this, as this cron is not handled by our module.

br,

**Comment by codeagencybe** [comment]
> Hello,
> 
> If the webhook isn't called, the cron will confirm the SO as a fallback system, and if enabled (not in your case) generate the invoice. The behavior i'm talking about ignoring the fresh orders can be found in the source code of Odoo. We also think this can be shorter, but it's not in the scope of Mollie, as it's default Odoo behavior. You can do this customisation easily by editing the behavior of that cron.
> 

I will have a look at this to see if it can help us with this issue. 

> The main issue in your case, is that the customer, somehow, is not going back to the redirect URL after a succesfull payment. This can be due to the end user closing his window too soon, or if you have it in 100% of the cases, a misconfigured base URL.
> 

Not possible. Because if the base url or redirect URL was wrong, then all payments would fail and have this problem. 
And it would also fail for Buckaroo and Stripe. 
So no, this is a wrong analysis from your end. 

> If you have it only for a few cases, than most likely it's the user closing the payment screen too soon.
> 

That could be a scenario, but not something we can control unfortunately. 

> Your solution in that case, is to alter the default Odoo cron to check even the freshly created ordes, instead of ignoring them the first X hours. Then it will be confirmed after 10 minutes instead after 12h or more.
> 
> If you think this behavior is not ok, you should contact Odoo about this, as this cron is not handled by our module.
> 

But even if this is default Odoo behavior, this conflicts with some other default behavior from Odoo.
Like abandoned cart emails. 
How it is designed by default means customers who made a succesful payment, but due to some callback issue, still receive a marketing email about some unpaid cart which they did pay for several hours earlier. 

Sorry to say, but this is a very poor designed flow by Odoo. And now we partners have to fix these broken flows? 
What a weird thing to propose.

**Comment by derekwolfson** [comment]
This happens to me with Stripe, too.

**Comment by alvaro2203** [comment]
Im having the same problem in odoo 16 with PayPal and Stripe. Any solution?

**Comment by codeagencybe** [comment]
There is none. Odoo considers this a feature, not a bug. 

We developed some helper function for our client so they can see the direct transaction record as a smart button on the quotation and also exposed it on the sale order list. 

Then create a filter that locks on transaction is set + status is quotation because this combination should not be possible and be a confirmed sale order. At least my customer can now easy identify the quotes that didn't confirm and do it manually. 

Also set the abandon cart email to long enough to avoid firing that one and upset end clients or completely disable abandon cart emails. 

Whatever odoo considered with this is just bar disgusting wrong and makes no sense.

**Comment by alvaro2203** [comment]
> There is none. Odoo considers this a feature, not a bug.
> 
> We developed some helper function for our client so they can see the direct transaction record as a smart button on the quotation and also exposed it on the sale order list.
> 
> Then create a filter that locks on transaction is set + status is quotation because this combination should not be possible and be a confirmed sale order. At least my customer can now easy identify the quotes that didn't confirm and do it manually.
> 
> Also set the abandon cart email to long enough to avoid firing that one and upset end clients or completely disable abandon cart emails.
> 
> Whatever odoo considered with this is just bar disgusting wrong and makes no sense.

Thanks for the reply, I agree with you that this should be fixed by Odoo.

**Comment by codeagencybe** [comment]
> > There is none. Odoo considers this a feature, not a bug.
> > We developed some helper function for our client so they can see the direct transaction record as a smart button on the quotation and also exposed it on the sale order list.
> > Then create a filter that locks on transaction is set + status is quotation because this combination should not be possible and be a confirmed sale order. At least my customer can now easy identify the quotes that didn't confirm and do it manually.
> > Also set the abandon cart email to long enough to avoid firing that one and upset end clients or completely disable abandon cart emails.
> > Whatever odoo considered with this is just bar disgusting wrong and makes no sense.
> 
> Thanks for the reply, I agree with you that this should be fixed by Odoo.

If you want to give your customer (or yourself?) at least some workaround, you can do it by doing something like this:

![Image](https://github.com/user-attachments/assets/3d71c246-9e30-4899-a768-10c78e1c1d79)

Under account > configuration > payment transactions you can see all confirmed transactions from your payment providers. 
If you open these, you will see there is a smart button that links to the sale order. 
But there is no reverse link (stupid) so even if a customer paid explicitly for a sale order, under accounting you can find it back and the quotation remains quotation. 

![Image](https://github.com/user-attachments/assets/f5f38aec-48df-4c57-bf5d-6a88667cc5ad)

So we customized this to link the payment transaction also from the sale order so now there is a 2-way link. 
And with this, we now have a field "payment_status" on the sale.order model which we can use to filter in the list so you can quickly see which "quotations" already have a payment confirmed so you can manually process them. 

I know it's not perfect, but at least you are not missing those orders and have angry customers who complain about their order is getting left behind while paid already (long time) because Odoo is too stupid to understand this is a serious operational malfunction.

**Comment by odoo-mvds** [comment]
Hi all,

Actually, if you let Odoo run this cron every 10 minutes, your order will be confirmed after maximum 1 day by this cron.
No need to do anything manually.

<img width="1535" alt="Image" src="https://github.com/user-attachments/assets/f2e38cf9-493e-4598-942a-ba324e3deaef" />

br,

**Comment by alvaro2203** [comment]
> Hi all,
> 
> Actually, if you let Odoo run this cron every 10 minutes, your order will be confirmed after maximum 1 day by this cron. No need to do anything manually.
> <img alt="Image" width="1535" src="https://private-user-images.githubusercontent.com/59664044/416208966-f2e38cf9-493e-4598-942a-ba324e3deaef.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NDA0MDQ3OTUsIm5iZiI6MTc0MDQwNDQ5NSwicGF0aCI6Ii81OTY2NDA0NC80MTYyMDg5NjYtZjJlMzhjZjktNDkzZS00NTk4LTk0MmEtYmEzMjRlM2RlYWVmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTAyMjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwMjI0VDEzNDEzNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTliZmEzMzhiZjMxZjY0YWZkYWY0NGY0MWY1NmE5Mjg5MjEwZDdhYTdjZmEzYzAzYjk4OTJhMDM1NDhkOTJjMzUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.uLVGZccxp83wiCG9GYWQZG8lLuk-GmFILNDCdqmLfSw">
> 
> br,

I understand that by executing this cron, the order will be confirmed in case the payment has been made, 

What about payments by bank transfer? For these cases the sales order is updated manually.

I only want it to be updated automatically when payment is received via PayPal, Stripe or credit card.

**Comment by odoo-mvds** [comment]
it will ignore the bank transfers as a bank transfer is not confirmed.

So it will work for u. However be patient, Odoo only processes the order that have a succesfull payment after a few hours.
Enable the cron and you will see that the order will become confirmed after a while.

br,

**Comment by codeagencybe** [comment]
> However be patient, Odoo only processes the order that have a succesfull payment after a few hours. Enable the cron and you will see that the order will become confirmed after a while.

This is exactly the problem. This "after a while" is random. Sometimes a few hours, sometimes up to 48 hours. Why??
Why do we need to wait more HOURS when Paypal, stripe, Mollie, ... already confirmed the payment was succesful? We already have the transaction available under accounting > configuration > payment transactions. It's right there. 

I don't understand why Odoo needs to decide to wait several hours to days when the actual PSP already decided the payment is valid and done??

Even with the scheduler set to run every 5 minutes, it makes no difference because there is another mechanism that holds back the actual confirmation for hours to days. 

And that is the complaint we have that makes no business logic sense. If it's paid, it's paid. Odoo should not interfere with the outcome from the payment provider, only pass it further and confirm it IMMEDIATELY, not hours later.

**Comment by odoo-mvds** [comment]
Hi,

This discussion needs to be done with Odoo... Not with us. I'm just explaining what Odoo does and am trying to help out @alvaro2203 

br,

**Comment by codeagencybe** [comment]
@odoo-mvds yeah, sorry your github name is confusing because you have odoo in it so it looks like you are from team odoo but you are from Mollie. 

But yes, we know this is a problem from Odoo, not from Mollie. Your platform does everything right. And again, this issue is not isolated to just Mollie, it also happens with Paypal and Stripe. 
We have reported this multiple times but Odoo does not consider it a bug nor a problem, even though many ecommerce companies are struggling with this. 🤷‍♂️

It makes me just mad they completely ignore these problems when they can easy solve this probably with a oneliner. 

It's just a bad implementation from Odoo to build in an artificial delay that should not be there. 
I can understand why they did this, probably it's just a safe guard if the callback fails so a cronjob will catch up later to avoid it never gets confirmed. But we don't understand why that specific delay is so huge (even up to 48h in several cases we have seen).
