### ISSUE TITLE
Migration Odoo 17

### ISSUE THREAD

**Issue by bobslee** [mollie/mollie-odoo#147]
Please could you let me know if there is any path for Odoo 17 migration or already in progress?

**Comment by Yenthe666** [comment]
@bobslee you know it is supported natively by Odoo now right? :)

**Comment by bobslee** [comment]
@Yenthe666 Yet I can't find how to reconcile Mollie payments/fees due to missing bank statements.
Is there any documentation available?

The `mollie_account_sync` module imported the settlements into bank statements, which is a simple process.

**Comment by Yenthe666** [comment]
Yeah they didn't take this over in the native app. Not even the syncing of payment methods.. 😞

**Comment by bobslee** [comment]
@Yenthe666 So my question is justified?

Do you know an alternative to reconcile the invoices paid by Mollie or different providers?

**Comment by Yenthe666** [comment]
Yes, at least for the `mollie_account_sync` app there is no default alternative unless you manually export/import or something. 
I haven't really come along an app to do this.

**Comment by odoo-mvds** [comment]
Hi,

The extended modules are planned to be released in March. In v17 the checkout system has been significantly changed by Odoo so we have more migration work than usual to do.

I'll send a message here when it's done.

br,

**Comment by bobslee** [comment]
Any update or expected release window for `mollie_account_sync` ?

**Comment by odoo-mvds** [comment]
Hi @bobslee we just released all v17 modules on the app store. mollie_account_sync has not been migrated because the mollie balance api is used in this new module, which is more accurate. See this link : https://apps.odoo.com/apps/modules/17.0/mollie_balance_sync/

**Comment by bobslee** [comment]
@odoo-mvds Thanks for the migration and answer!
