### ISSUE TITLE
[17.0] payment.icon no longer exists

### ISSUE THREAD

**Issue by jwaes** [mollie/mollie-odoo#152]
https://github.com/mollie/mollie-odoo/blob/afd215e17cdbf3f54bc4a013484fdf9c63ee60d0/payment_mollie_official/models/mollie.py#L15

there is no longer a payment.icon model in odoo 17.0
https://github.com/odoo/odoo/tree/17.0/addons/payment/models

**Comment by odoo-mvds** [comment]
Hello,

Actually, the `mollie.payment.method.issuer` table is obsolete in version 17. It has been removed in the updated version `17.0.0.2`.

Thank you for bringing this to our attention.
