### ISSUE TITLE
General improvement tips

### ISSUE THREAD

**Issue by Yenthe666** [mollie/mollie-odoo#16]
Hi guys,

Thanks again for releasing V12. I found a few things that could/should be improved.
- Add `_description` on the models `payment.acquirer.method`, `provider.log` and `force.update.data` so that Odoo.sh and runbot instances give no warnings
- Don't use built in names such as `type`
https://github.com/mollie/mollie-odoo/blob/a2ecb8cb9f0577c973161605d622de023f5c92fd/payment_mollie_official/models/provider_log.py#L43
- Make `clean_old_logging` day amount configurable
https://github.com/mollie/mollie-odoo/blob/a2ecb8cb9f0577c973161605d622de023f5c92fd/payment_mollie_official/models/provider_log.py#L47
- Make default payment method values configurable?
https://github.com/mollie/mollie-odoo/blob/a2ecb8cb9f0577c973161605d622de023f5c92fd/payment_mollie_official/models/mollie.py#L39-L55

CC @gclauwae

**Comment by gclauwae** [comment]
Hi Yenthe, Thanks for the feedback. The amounts in the DEFAULT_METHOD_VALUES are configurable in the Gateways view.
![Min_Max_Mollie_Gateways](https://user-images.githubusercontent.com/23232587/54342929-ecb8e380-463d-11e9-9868-f7172a785aa4.PNG)

**Comment by Yenthe666** [comment]
Aha, I didn't notice that, my bad. You can ignore that one then :)
