### ISSUE TITLE
[12.0] Mollie Test & Live API key overwritten on module update

### ISSUE THREAD

**Issue by mgielissen** [mollie/mollie-odoo#18]
Settings for Mollie Test & Live API key field are overwritten on module update (resets to "mollie api test key").

**Comment by gclauwae** [comment]
Hi, From a user perspective I agree that this is frustrating. From a security point of view it's rather OK. I'll talk to Mollie and let them decide.

**Comment by Yenthe666** [comment]
Nah, this was totally not logical in any case. What would it change in the security point of view that a module on update automatically drops an API token? I've actually changed and handled this inside of another commit. See https://github.com/mollie/mollie-odoo/commit/4ca9bf1ae01b763e01df5521247608face9cbc70

Edit: to be clear.. the API keys will no longer be overwritten now.
CC @martijnpolder
