### ISSUE TITLE
[12.0] No Mollie payment icon available under user portal My Invoices - Pay Now

### ISSUE THREAD

**Issue by karsih** [mollie/mollie-odoo#23]
The Mollie payment icon is not available  in the user portal **My Account/Invoices - Pay Now** screen.

**Comment by Yenthe666** [comment]
Hi @karsih,

Could you please update to the latest 12.0 version and check again? There have been quite some updates and fixes in the last weeks.

Regards,
Yenthe

**Comment by mgielissen** [comment]
With the latest updates the payment icon is still not available.

**Comment by Yenthe666** [comment]
@mgielissen could you share your configurations/settings?
Do you see the icons under the configuration of the Mollie provider like this?
![image](https://user-images.githubusercontent.com/6352350/57457686-43beeb80-7270-11e9-9cca-63c78715b3ab.png)
What do you get on the payments screen? Example:
![image](https://user-images.githubusercontent.com/6352350/57457860-9ac4c080-7270-11e9-9e5c-1f529fee36be.png)

**Comment by mgielissen** [comment]
Steps to reproduce:

1. Install v12 db with demo data
2. install mollie addon 
3. Config Mollie addon
4. Enable online invoice payments
![afbeelding](https://user-images.githubusercontent.com/7700396/57458334-73222800-7271-11e9-8bad-33cae9e5365b.png)
5. Order in shop shows Mollie payment icons
![afbeelding](https://user-images.githubusercontent.com/7700396/57458630-f9d70500-7271-11e9-83cd-57122552bc67.png)
6. Online payment only shows Wire Transfer
![afbeelding](https://user-images.githubusercontent.com/7700396/57458585-e9268f00-7271-11e9-9900-71514e7dd937.png)

**Comment by Yenthe666** [comment]
@mgielissen and @karsih aha, I get what you guys mean now! This is actually not added/supported in the official Mollie app right now.
It is on the roadmap so it will most likely be added in V13, allowing you to choose Mollie payment methods on invoices from the portal.

**Comment by mealhero** [comment]
Any update on this?

**Comment by mgielissen** [comment]
FYI: there is another (paid) Mollie module that works with portal invoices.

**Comment by mealhero** [comment]
I think it's very strange that the official Mollie module doesn't support this and we are referred to a paid third party module

**Comment by Yenthe666** [comment]
It was actually confirmed on the roadmap for V13. I started working on related things for this in 2019 but then moved to another company. The company I've worked for is still responsible for implementing this though. I guess you can reach out to Mollie themself about a timeline/status update. They don't really keep track of the Github issues themself.

**Comment by mealhero** [comment]
Once again I would like to ask the status of this feature. Is an ETA available?

**Comment by MerijnMollie** [comment]
Hi @mealhero, thanks for bringing this up. Please note that this feature is planned for early Q3.

**Comment by odoo-mvds** [comment]
Hello all,

v12 & v13 to be released soon. This will be supported and being tested in beta as we speak.

**Comment by Ryukenn** [comment]
hey, i have a similar problem.  
I have no icons under the configuration of the Mollie providers as shown in the first screenshot of  @Yenthe666 . 
I don't know what i did wrong and am stuck right now.
I'm useing v13 of mollie and the newest odoo version. would be awesome if someone could point me into the right direction. 
thanks in advance!

**Comment by odoo-mvds** [comment]
Hello, the new version is released. Paying invoices from my portal is working now using the payment API of mollie.
