### ISSUE TITLE
[12.0] no validation feedback for invoice address

### ISSUE THREAD

**Issue by ghost** [mollie/mollie-odoo#30]
When filling in the invoice address to place your order in the webshop there is no feedback telling the user that the phone number is invalid or postal code is required for example.

This is a problem when you want to pay with a mollie related payment method. 
The user gets redirected to the home page without feedback. Only in the server logs we can see what went wrong:
`odoo.addons.payment_mollie_official.models.sale_order: ERROR! The following fields of the billingAddress are missing: postalCode`

Is this something that can be configured? 

This is really annoying and the customers don't know what is happening.

**Comment by Yenthe666** [comment]
@BryanStael this has been fixed in https://github.com/mollie/mollie-odoo/commit/4ca9bf1ae01b763e01df5521247608face9cbc70
There is a minor improvement for the ZIP incoming at https://github.com/mollie/mollie-odoo/pull/31
CC @martijnpolder

**Comment by Yenthe666** [comment]
The ZIP fix has also been done (https://github.com/mollie/mollie-odoo/commit/4ceaa50056a6f6ade1a64063a1b913aa49f11636) so all the issues should be solved now.
