### ISSUE TITLE
Could you create a 9.0 branch from the 10.0 ?

### ISSUE THREAD

**Issue by houssine78** [mollie/mollie-odoo#36]
Hi there,

I've backported the branch 10.0 to 9.0 for a customer project. Could you create a 9.0 branch from the 10.0 in order to allow me to propose a PR on the new branch ?

Thanks!

**Comment by houssine78** [comment]
@Yenthe666 I don't know who to tag to have this done so I ping you just in case.

**Comment by Yenthe666** [comment]
Hi,

I'm actually the main developer for Mollie at this point :) I'll check with the functional guys from Mollie to see if they're open to making a backport and making it available on V9.
I'll get back to you.

**Comment by houssine78** [comment]
@Yenthe666 good to know ;)

thank you !

**Comment by houssine78** [comment]
Hi @Yenthe666  did you get any new from the guys from Mollie ?

Thanks !

**Comment by Yenthe666** [comment]
Sorry I haven't heard back yet :( @Smitsel would you be fine with this?

**Comment by houssine78** [comment]
@Yenthe666 we may also be interested to develop a module for subscription payment (handling subscription in Odoo) in case of there is some interest.

**Comment by ghost** [comment]
Hi, There will be no version 9. Basically Mollie will follow the support cycle of odoo and that means, V11,, V12 and V13. If needed we will fix bugs in V10 also, but no older versions are created. Thanks for understanding.
