### ISSUE TITLE
Update payment methods every 5 minutes via cron

### ISSUE THREAD

**Issue by Peltier1977** [mollie/mollie-odoo#39]
Hi,
My system is very limited in resources and it crashes once a day ...
Finally i found it crashs right after the update "Update payment methods" cron job (last night, nothing else happend).

It updates every 5 minutes, Why?
From my pint of view, i will update payment methods myself via Gui Button when i need it!

Is it save to delete that cron job (ir_cron) from DB or will the addon insert that job again after restart?
Or is it needed for somthing else?

Thx

**Comment by Yenthe666** [comment]
It updates and syncs all payment methods automatically for a reason. It will detect a deactivation or activation of a payment method on the Mollie website itself. I wouldn't advise you to remove it and as it is a very small and light cron job it really shouldn't crash your system. I assume you run a way too light server ;)
If you really want to you can remove the cron but then you also have to remote the Python code for the function or you'll get errors in the logs all the time.

**Comment by Peltier1977** [comment]
I did delete the cron job yesterday, server is still up and looks ok so far. Business will start soon, before that we will migrate to a larger hosting solution.
One finall Question - how can i restore that corn job (Unfortunately i did not take notes ....)?

**Comment by Yenthe666** [comment]
If you've deleted the cron (so really clicked delete) you should be able to update the module and then the module should recreate it. Take a backup & note of your configurations before doing so to be safe though.
