### ISSUE TITLE
Mollie Bank statements sync

### ISSUE THREAD

**Issue by mealhero** [mollie/mollie-odoo#44]
wishlist: automatically sync all transactions in Mollie to bank statements in a Odoo journal (so invoices can be reconciled easily).

**Comment by codeagencybe** [comment]
Great idea @mealhero !

**Comment by ghost** [comment]
See: https://github.com/mollie/mollie-odoo/tree/13.0/mollie_account_sync

**Comment by mealhero** [comment]
I have installed the latest version of this module and entered my mollie api key to "online payment acquirers/Mollie" and put it into production mode. I have enabled Mollie Synchronisation in the Mollie bank account journal I had made. If I click on "Sync Mollie" it still asks me to enter an API key (but no field to input this key". What am I doing wrong?



                  <li> Install the module. </li>
                    <li> Open Journal Settings </li>
                    <li> Open <b> Bank Account </b> tab </li>
                    <li> Select <b> Bank feeds = Mollie Synchronization </b> </li>
                    <li> Add your <b> mollie api key. </b> </li>

**Comment by mealhero** [comment]
Also, the field "Live API key" is just plain text: everybody with access to settings can see and copy the live api key?!
