### ISSUE TITLE
[12.0]Callback to site after payment fails or gets cancelled

### ISSUE THREAD

**Issue by jderid** [mollie/mollie-odoo#46]
https://github.com/mollie/mollie-odoo/blob/7bbba2f270f6789117af4212286415c0ef34faea/payment_mollie_official/controllers/main.py#L55

There appears to be an issue here with the redirect. 
The issue happens when cancelling a payment after being redirected to the mollie page. 
This happens in test or production mode.
I made a video of the case:
https://drive.google.com/file/d/1Qyl9jAaZPFmLDU_ZqHZyvq3FLSZB0K12/view

The most anoying part of this issue is hat behaves like the payment has completed and empties the customer they shopping cart.

**Comment by ghost** [comment]
Dear Krynox,

Thank you for reporting the issue.
We will investigate why this is happening and will get back to you.

Best regards,
Diederik Wesselink

**Comment by ghost** [comment]
The problem has been solved by #49
