### ISSUE TITLE
Field 'image' missed on model payment.acquirer

### ISSUE THREAD

**Issue by Terroirsdavenir** [mollie/mollie-odoo#53]
Hello,

The image field is not declared in payment.acquirer model.
Please add this field.

Regards,

**Comment by ghost** [comment]
@Terroirsdavenir Hello
In v13, the field name is "image_128" for the payment.acquirer model
and it is already declared in the odoo addons v13.
https://github.com/odoo/odoo/blob/13.0/addons/payment/models/payment_acquirer.py#L160
https://github.com/odoo/odoo/blob/13.0/addons/payment/views/payment_views.xml#L18

and
In v12, there are 3 image fields,
image
image_medium
image_small
for the payment.acquirer model
and it is already declared in the odoo addons v12.
https://github.com/odoo/odoo/blob/12.0/addons/payment/models/payment_acquirer.py#L154
https://github.com/odoo/odoo/blob/12.0/addons/payment/views/payment_views.xml#L52

**Comment by ghost** [comment]
@tarteo Thank you for the patch to master branch.
https://github.com/mollie/mollie-odoo/pull/55/commits/b6b2f5c62dd366a64bee2ae852f46bd7d84314f1
https://github.com/mollie/mollie-odoo/pull/55/commits/794d87b7a70f41f28b41f96b0e922dd9660b05f8
