### ISSUE TITLE
local variable 'api_key' referenced before assignment

### ISSUE THREAD

**Issue by Terroirsdavenir** [mollie/mollie-odoo#54]
Hello,

In the _get_mollie_api_keys method, the local variable 'api_key' is called before assignment.
You have to deal with the case where the state is disabled

Regards,

**Comment by ghost** [comment]
@Terroirsdavenir Hello
I think you are checking in the "master" branch.
You should checkout the branch "13.0" and check further.

The variable "api_key" is using in the "master" branch.
https://github.com/mollie/mollie-odoo/blob/master/payment_mollie_official/models/payment_acquirer.py#L50 

And the "13.0" branch, there is no issue related to the variable.
https://github.com/mollie/mollie-odoo/blob/13.0/payment_mollie_official/models/payment_acquirer.py#L74

**Comment by odooexpertsbv** [comment]
@te
