### ISSUE TITLE
Invalid payment ID

### ISSUE THREAD

**Issue by DanbaVanBit** [mollie/mollie-odoo#57]
Hi,
I'm testing mollie v13 on a new test instance and i'm getting an Internal server error when finishing the payment in the mollie portal and getting back to the store.
The server log reports an Invalid payment ID, but the mollie log shows a correct payment id.
I've tried it in test mode and in live mode with similar results.
Any idea's how to fix this?
![2020-04-06_10h18_59](https://user-images.githubusercontent.com/40424534/78538962-1b2dd180-77f2-11ea-9063-590282fd5ef0.png)
![2020-04-06_10h21_21](https://user-images.githubusercontent.com/40424534/78539008-2b45b100-77f2-11ea-9d33-92fc913f1a18.png)
![2020-04-06_10h22_26](https://user-images.githubusercontent.com/40424534/78539016-2ed93800-77f2-11ea-9229-0edd7337a3aa.png)

**Comment by ghost** [comment]
Please do the git pull for Odoo, [this Commit](https://github.com/odoo/odoo/commit/276f22c49511ba33b50eda242f39ecbd76e967a9) is solving the problem.
