### ISSUE TITLE
dependancy on stock module

### ISSUE THREAD

**Issue by odoo-mvds** [mollie/mollie-odoo#59]
Beste,

nieuwe klant heeft de module stock niet nodig. Echter installeert jullie module deze module als dependancy. Is dit echt nodig? Kost de klant teveel geld, en is een no go als dit zo is...

gr,

**Comment by ploegvde** [comment]
De afhankelijkheid van de stock app is verwijderd vanaf versie 13. Wellicht is het mogelijk om versie 13 te gebruiken.

**Comment by odoo-mvds** [comment]
Beste,

De versie die wij gebruiken is Odoo v12. Het is niet mogelijk om versie te
mengen. Jullie zouden de build van v12 ook moeten goed zetten...
Met vriendelijke groeten,
<https://www.facebook.com/vdsitsolutions> <http://www.vdsit.be/>
Michael Vandesompel
Zaakvoerder
24/7 SUPPORT:
+32 59 795 111
E‑MAIL SUPPORT:
mv@vdsit.be


Op di 7 apr. 2020 om 08:50 schreef Erwin van der Ploeg <
notifications@github.com>:

**Comment by mgielissen** [comment]
Er is een andere Mollie module (wel betaald) voor v12 die geen stock nodig heeft.

**Comment by ghost** [comment]
@odoo-mvds Ik begrijp je opmerking, maar binnen een stabiele versie zullen we geen aanpassingen van deze omvang doorvoeren.
