### ISSUE TITLE
familyName contains whitespace characters

### ISSUE THREAD

**Issue by PCatinean** [mollie/mollie-odoo#69]
Whenever a user is registered with a name that contains whitespaces we get this:

odoo.addons.payment_mollie_official.models.sale_order: ERROR! The 'familyName' field should not contain only whitespace characters

Looking at the way it's generated it only makes sense:
https://github.com/mollie/mollie-odoo/blob/12.0/payment_mollie_official/models/res_partner.py#L38

**Comment by ghost** [comment]
Fix available at #68

**Comment by ghost** [comment]
@PCatinean thank you for report. you can find fix at #68
