### ISSUE TITLE
Multi-company support (multiple Mollie providers)

### ISSUE THREAD

**Issue by Manuel-Dellisse** [mollie/mollie-odoo#73]
Hi,

Discovered that Mollie uses the first provider it can find ordered by ID, and doesn't take into account of multi-company.
A pull-request #72 is available for review.

Looking forward from hearing you.

Sincerely,
Manuel Dellisse

**Comment by odoo-mvds** [comment]
Hello,

the new versions supports multi company. To be released in August.

br,

**Comment by ghost** [comment]
@Manuel-Dellisse 
@odoo-mvds 
Hello
FYI
The PR https://github.com/mollie/mollie-odoo/pull/72/ for version 12 has been already merged into the 12.0 branch.

**Comment by odoo-mvds** [comment]
New version was release a few days ago. It supports webhooks, mollie components and fully tested in multi company DB's. We advice you to upgrade to this version. Please do this on a staging server first if your are not doing a clean install of the module.
