### ISSUE TITLE
Partial refund

### ISSUE THREAD

**Issue by mgielissen** [mollie/mollie-odoo#77]
Is it possible to make a partial refund?

**Comment by ghost** [comment]
Hello @mgielissen 
Yes, we can make the partial refund.
For the partial payment working in odoo-mollie,
please refer these steps and all attached files.

For e.g.

Step 1 : Create an invoice (account.move) of 100 prices and make payment via mollie. 
Please refer Step1.png
![Step1](https://user-images.githubusercontent.com/39831642/93670202-3e55f000-fab7-11ea-9133-5fa6877df2f9.png)


Step 2 : After the payment, the record has been created for 100 amount for that invoice on the mollie account.
Please refer Step2.png
![Step2](https://user-images.githubusercontent.com/39831642/93670203-43b33a80-fab7-11ea-9622-1d7da6f4e8a2.png)


Step 3 : In the invoice (account.move) record click on "ADD CREDIT NOTE" button, a popup will be open and fill the details on that popup and after click REVERSE on the popup, the new record will be created for partial refund.
Please refer Step3.png
![Step3](https://user-images.githubusercontent.com/39831642/93670205-49108500-fab7-11ea-87ff-eef82317a56b.png)


Step 4 : We have to add the amount which we want to refund after that click on POST in the newly created record for the partial refund and then click on "MOLLIE REFUND" buttons.
Please refer Step4.png
![Step4](https://user-images.githubusercontent.com/39831642/93670208-4e6dcf80-fab7-11ea-9d62-e51fc2112150.png)


Step 5 :  After clicking "MOLLIE REFUND", the record will be PAID and refund record will be created on mollie account.
Please refer Step5.png
![Step5](https://user-images.githubusercontent.com/39831642/93670210-5299ed00-fab7-11ea-9fd9-d5f061ae7549.png)


Step 6 : On the refund menu, we can see the created record with the refund amount.
Please refer Step6.png
![Step6](https://user-images.githubusercontent.com/39831642/93670212-575ea100-fab7-11ea-9bb9-fb4da55454ae.png)


Step 7 : As per the example, 50 amount is refunded from 100 amount for that record which has been partially refunded.
Please refer Step7.png
![Step7](https://user-images.githubusercontent.com/39831642/93670214-5af22800-fab7-11ea-9702-6dc3e71dab40.png)
