### ISSUE TITLE
ERROR! on Create order

### ISSUE THREAD

**Issue by wilfriedsip** [mollie/mollie-odoo#80]
Hello,

I just installed the Mollie V13 and with no error.

But something goes not good, when we do an order on the website and choose mollie it goes back to the font page.
In the loggin from Mollie I get the error "ERROR! on Create order"
The redirect URL is invalid {'amount': {'value': '1.21', 'currency': 'EUR'}, .........

Who can help me or point me in the right direction.
Thanks

**Comment by ghost** [comment]
@wilfriedsip Hello
I think you should do the proper configuration like "Mollie Live API key" or "Mollie Test API key" which should be based on the mollie state. 
There are 3 configuration values in the "State", 
like 'Disabled' for deactivating mollie,
'Enabled' for mollie live API key,
and 'Test Mode' for mollie test API key.

Thank you

**Comment by wilfriedsip** [comment]
@odooexpertsbv Hello,
Thank you for your answer but we did put in the "Mollie Test Api key". and put the state to Test Mode.
Also we tried the Mollie Live API key and set it to Enable but no result.

On the moment we try to do a payment it go back to our frontpage and in the backend we get by the mollie loggin we get the message ERROR! on Create order. The redirect URL is invalid.......
If paste the redirect url in my browser it is also not going to Odoo but I receive a message.
Internal Server Error

The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.

maybe you can point me in the right direction.

Thank again for the help

**Comment by ghost** [comment]
@wilfriedsip Hello
Can you please share with us the whole error log?
So we will have an exact idea about the cause and we will proceed further accordingly.

Thank you
