### ISSUE TITLE
Sequence number payment method issue

### ISSUE THREAD

**Issue by Agacolor** [mollie/mollie-odoo#85]
We have installed the mollie payment module in V12 enterprise (odoo.sh). 
When configuring the payment gateway settings it is possible to sequence and deactivate the various payment methods.
However: this does not seem to have an effect on the front end where users select the payment method.

![frontend-backend](https://user-images.githubusercontent.com/60174039/94375768-590f1100-0116-11eb-87f8-034aa9fcf90b.png)

**Comment by odoo-mvds** [comment]
Hello,

this issue is only related to v12. We will fix it soon.

br,

**Comment by odoo-mvds** [comment]
Hello,

this issue was solved yesterday. Please update the module.

br,

**Comment by Agacolor** [comment]
thanks!
Looks ok at first glance.👍

Op za 14 nov. 2020 om 09:33 schreef odoo-mvds <notifications@github.com>:
