### ISSUE TITLE
Odoo V14 support

### ISSUE THREAD

**Issue by Yenthe666** [mollie/mollie-odoo#86]
Hi there,

When will the V14 app of Mollie be released?
Is there a timeline?

**Comment by Yenthe666** [comment]
@odoo-mvds @Smitsel could one of you let me know please? I need it for a project :)

**Comment by odoo-mvds** [comment]
Hello Yenthe,

It's ready and we think to release it today or tomorrow.

br,

**Comment by Yenthe666** [comment]
Nice, thanks a lot! I have two customers going to V14 very soon so we can test it ASAP :)

**Comment by odoo-mvds** [comment]
Hello,

V14 was released. You can test it.

br,

**Comment by Yenthe666** [comment]
Awesome, thanks :) For your interest: it's not yet published on the appstore & the readme is still in V13.
