### ISSUE TITLE
Confirm order shipment when Klarna payment is used

### ISSUE THREAD

**Issue by mgielissen** [mollie/mollie-odoo#96]
When a website order is paid with Klarna (payment afterwards), the shipment must be confirmed in the mollie.com dashboard. It would be nice if the shipment can be confirmed in Odoo.

**Comment by odoo-mvds** [comment]
Hi,

This module has been released for v12, 13 & 14. See this link:
https://apps.odoo.com/apps/modules/14.0/mollie_shipment_sync/

br,
