### ISSUE TITLE
Payment link iDEAL error 'Non-existent body parameter "payment.issuer" for this API call.'

### ISSUE THREAD

**Issue by VincentMollie** [mollie/mollie-odoo#97]
A merchant is trying to send payment links to his customers, but is getting above error every time when trying to pay with iDEAL. I checked the normal checkout in the webshop and I can complete iDEAL orders just fine there. Any idea why it doesn't work for payment links specifically?

They are on 13.0.1.3. You can see for yourself here: https://www.versusshop.nl/my/orders/3129?access_token=d62d0bbe-1b59-4892-89fb-33292e0c1584&auth_signup_token=WJkb5d7S1idI1QD3enm3

I tried Bancontact and SOFORT as well, but there I'm getting the error that the amount is lower than the minimum. This is strange as the minimum is set to 0.01 at Mollie.

**Comment by wilfriedsip** [comment]
We are having the same problem, A customer
<img width="1411" alt="Screenshot 2021-01-07 at 21 45 48" src="https://user-images.githubusercontent.com/60424738/103943089-bfea9000-5131-11eb-96f1-6961a3a61e6e.png">
 is trying to do a payment and receiving this error.
I tried to make a payment myself and everything is working perfect.
But no matter what she tries she get every time this error.

**Comment by odoo-mvds** [comment]
Hello,

ZIP code is mandatory. If you make the field mandatory during checkout this problem will be solved.

br,

**Comment by Yenthe666** [comment]
Maybe you should do it in code instead of saying this to random people 😆
