### ISSUE TITLE
"not able to redirect you" "account.move.line object has no attribute always_set_currency_id" with mollie and odoo 14

### ISSUE THREAD

**Issue by numabit** [mollie/mollie-odoo#98]
![image](https://user-images.githubusercontent.com/69018770/103457184-308e4880-4cfd-11eb-86f4-7a8e49cbbeeb.png)

**Comment by odoo-mvds** [comment]
Hello,

It seems this issue is related to the currency configuration of your instance... Can you double check your configuration first? Is it normal you are using multi-currency? 

Which version are you using? CE or EE? We need more information than this to be able to help you.

br,

**Comment by numabit** [comment]
Hello,

I’ve installed the plugin on a clean install of odoo 14 CE running on Debian 10.
The main currency is set to “EUR” and we are not using multi-currency.

Which configs in odoo 14 should I check?

FYI "I have no problems in Odoo 13 CE" 


If you want I can make a login for you on our system?

Kind regards
Niels

**Comment by numabit** [comment]
CE version 😊

Van: Info | Numabit.com
Verzonden: Saturday, January 9, 2021 2:55 PM
Aan: mollie/mollie-odoo <reply@reply.github.com<mailto:reply@reply.github.com>>
Onderwerp: RE: [mollie/mollie-odoo] "not able to redirect you" "account.move.line object has no attribute always_set_currency_id" with mollie and odoo 14 (#98)

Hello,

I’ve installed the plugin on a clean install of odoo 14 running on Debian 10.
The main currency is set to “EUR” and we are not using multi-currency.

If you want I can make a login for you on our system?

Kind regards
Niels



Van: odoo-mvds <notifications@github.com>
Verzonden: Saturday, January 9, 2021 8:28 AM
Aan: mollie/mollie-odoo <mollie-odoo@noreply.github.com>
CC: Info | Numabit.com <info@numabit.com>; Author <author@noreply.github.com>
Onderwerp: Re: [mollie/mollie-odoo] "not able to redirect you" "account.move.line object has no attribute always_set_currency_id" with mollie and odoo 14 (#98)


Hello,

It seems this issue is related to the currency configuration of your instance... Can you double check your configuration first? Is it normal you are using multi-currency?

Which version are you using? CE or EE? We need more information than this to be able to help you.

br,

**Comment by numabit** [comment]
Any news?

**Comment by odoo-mvds** [comment]
Hello,

please send an email to mv@applix.be
I will have a look on your DB.

br,

**Comment by odoo-mvds** [comment]
Hello,

the new version with the fix has been released today. Please update the module and test again.
https://apps.odoo.com/apps/modules/14.0/payment_mollie_official/

br,
