### ISSUE TITLE
ERROR Message: Webhook URL is invalid

### ISSUE THREAD

**Issue by ThorOdoo** [mollie/mollie-odoo#99]
In December we installed Mollie for our Odoo CE V13. Since then the payment method is not working with our system. 
From the beginning we got the following two error-messages as pop-up in the payment exit process in our webshop:

1. Trying with Mollie to pay via PayPal: "Payment method is not supported. Try another payment methord or contact us
Error Message: The webhook URL is invalid because it is unreachable from Mollie's point of view." 
2.  Trying to use Klarna, CreditCard as Payment Method trough Mollie: "Payment method is not supported. Try another payment methord or contact us. Error Message: The webhook URL is invalid" 

We could not find any Error-Log in Odoo System, only this pop-up showing up.
We reached out for the support and followed all their instructions: reinstalled the modul, made sure it's the newest version (13.0.1.3), but same problem. Then Mollie Support tried to make a payment themselves to check the API-Key. That worked. But out of our shop we still get the webhook error message. So they aksed us to reach out to you here. 
Our Odoo expert tried to find out, why Mollie can't reach the webhook, but could not find anything. So could you tell us, where to place the webhook, Mollie can reach out to it?
Therefore we appreciate your help 

Best regards

**Comment by AmandaMollie** [comment]
@ThorOdoo - I believe the FIX should be available in the next release, which is expected next week. @odoo-mvds - Can you please provide any additional details?

**Comment by odoo-mvds** [comment]
@ThorOdoo we also saw many bad NGINX settings.
I don't think this is a module error.

The new version was released, please download it and try it. But if the same issue is still there you should look at your reverse proxy settings.

br,

**Comment by ThorOdoo** [comment]
@odoo-mvds Thanks for your answer. Could you tell us how the proxy and NGINGX settings must look like? And do you have experience with odoo in combination with admin-panel Keyhelp (stettings)? Our server manager is not as familiar with odoo and before we set up a test server to reinstall Odoo completly we`d like to pull all other strings.
br

**Comment by odoo-mvds** [comment]
I'm sorry, that's not our domain or expertise. We just know that the proxy need to be correctly configured so that Mollie knows where to reach your website. The error that you mentioned seems to point in that direction. You should contact someone that has experience on nginx.
